version: '3.9'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - app-tier
  nodejs:
    restart: on-failure
    build: ./
    ports:
      - '8080:8080'
    networks:
      - app-tier
    depends_on:
      - redis