version: '3.9'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - app-tier
    volumes:
    - cache:/data

  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - '27017:27017'
    networks:
      - app-tier
    volumes:
      - db:/data/db

  nodejs:
    restart: on-failure
    build: ./
    ports:
      - '8080:8080'
    networks:
      - app-tier
    depends_on:
      - redis
      - mongodb

volumes:
  db:
    driver: local
  cache:
    driver: local